version: "3.8"

services:
  backend:
    build: .
    container_name: ssb-backend
    tty: true
    stdin_open: true
    restart: always
    ports:
    - "8001:8111"
    volumes:
      - ./:/srv/project
    depends_on:
      - memcached
      - rabbitmq
    env_file:
      - .env

  memcached:
    image: memcached:1.6.9
    container_name: memcached
    tty: true
    stdin_open: true
    restart: always

  rabbitmq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbitmq
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .env
    ports:
      - "15672:15672"

  postgres:
    image: postgres:12
    container_name: ssb-db
    tty: true
    stdin_open: true
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"


