# Generated by Django 3.1.7 on 2021-05-27 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
