# Generated by Django 3.1.7 on 2021-04-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210403_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.AlterModelTable(
            name='subscriber',
            table='tb_subscribers',
        ),
    ]
