# Generated by Django 3.1.7 on 2021-03-28 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок поста')),
                ('description', models.TextField(max_length=90, verbose_name='Описание поста')),
                ('content', models.TextField(verbose_name='Контент поста')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=80, verbose_name='Почта')),
            ],
            options={
                'db_table': 'db_users',
            },
        ),
    ]
