# Generated by Django 3.1.7 on 2021-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='last_name', max_length=90, verbose_name='Фамилия автора'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email_to', 'author_id')},
        ),
    ]
