# Generated by Django 3.1.7 on 2021-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.PositiveSmallIntegerField(choices=[(1, 'advertisments'), (2, 'news'), (3, 'weather'), (4, 'business'), (5, 'info')], default=5),
        ),
    ]
