# Generated by Django 3.1.7 on 2021-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210410_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm', models.CharField(max_length=20, verbose_name='UTM метка')),
            ],
        ),
    ]
