# Generated by Django 3.1.7 on 2021-04-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210412_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='active',
            new_name='activate',
        ),
    ]
