# Generated by Django 3.1.7 on 2021-04-19 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Имя автора')),
                ('last_name', models.CharField(blank=True, max_length=90, verbose_name='Фамилия автора')),
                ('email', models.EmailField(max_length=80, verbose_name='Почта автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'db_table': 'tb_users',
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm', models.CharField(max_length=50, verbose_name='UTM метка')),
                ('time_execution', models.CharField(max_length=70, verbose_name='Время выполнения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=70, verbose_name='Path')),
                ('user_ip', models.CharField(max_length=20, verbose_name='IP адрес пользователя')),
            ],
            options={
                'db_table': 'tb_loggers',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок поста')),
                ('description', models.TextField(max_length=90, verbose_name='Описание поста')),
                ('content', models.TextField(verbose_name='Контент поста')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'tb_posts',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=80, verbose_name='Почта подписчика')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'db_table': 'tb_subscribers',
                'unique_together': {('email_to', 'author_id')},
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментариий')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('activate', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post')),
                ('subs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subscriber')),
            ],
            options={
                'db_table': 'tb_comments',
                'ordering': ('created',),
            },
        ),
    ]
